version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - ngrok
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2jgUTMFs3hqTzcxxxxxxxxxx (replace with your own token)
    command: http nginx:80
    networks:
      - ngrok

  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    command: gunicorn -c g_config.py app:app --bind 0.0.0.0:8000 --reload
    volumes:
      - ./flask_app:/app
      - ./log:/var/log/gunicorn
    networks:
      - ngrok
    expose:
      - "5000"

networks:
  ngrok:
    driver: bridge
